# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - mai-mind-map

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: npm install, build, and test
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build --if-present
          npm run test --if-present
          cd mai-mind-map-se
          pnpm install
          pnpm run build:server
          cd ..
          cd office-addin
          pnpm install
          pnpm run build
          cd ..

      - name: Zip artifact for deployment
        run: |
          cd mai-mind-map-se
          zip release.zip ./* -r
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./mai-mind-map-se/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        env:
          APP_CONFIG: ${{ secrets.APP_CONFIG }}
        shell: bash
        run: |
          unzip release.zip
          echo "$APP_CONFIG" > config.json

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_61F9B8B7CA6745E290DC921D21EDAAFA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D0DF6CC7437476FBB33533634A99E0B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_56F7BDBFFDB245B797A79A1F92E77DA5 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mai-mind-map'
          slot-name: 'Production'
          package: .
